### ISSUE TITLE
Can two different workspaces be connected to different google accounts?

### ISSUE THREAD

**Issue by garymcm** [MaartenDesnouck/google-apps-script#107]
Question is self explanatory I hope. I am keeping Development in a different project in a different account. 

Right now I gas auth -f to switch connections.

Dev -> gas push -> Dev Project
 |
git pull
 |
Prod -> gas push-> Prod Project

**Comment by MaartenDesnouck** [comment]
Not possible at this time... will think about this.

**Comment by garymcm** [comment]
I mean to say, this is a really elegant utility you've created. Thank you, Maarten.
