### ISSUE TITLE
Ignore certain files?

### ISSUE THREAD

**Issue by Jakobud** [MaartenDesnouck/google-apps-script#108]
Is it possible to ignore certain files? So when you do a blanket `gas push` it doesn't upload certain files? Sort of like a gitignore but for gas? Cause otherwise Google Apps Scripts returns errors for unsupported file types.

For example if you have some other things in your directory like a package.json or some Node.js scripts for compiling SASS > CSS, etc... Any of that stuff gas tries to upload it when you `gas push` and then it throws errors.

**Comment by MaartenDesnouck** [comment]
Duplicate of #69
