### ISSUE TITLE
`gas push` results in Error "Can't seem to find <FILE> in local filesystem"

### ISSUE THREAD

**Issue by radiovisual** [MaartenDesnouck/google-apps-script#124]
Attempting to use `gas push` on any existing files, results in an Error that the file it is trying to push can't be found on the local filesystem.

![image](https://user-images.githubusercontent.com/5614571/49735473-95deef00-fc87-11e8-8b59-592834c8bba8.png)

```
❯ gas --version                                                                                                                      
4.1.2

❯ node --version                                                                                                                     
v8.10.0
```

**Comment by radiovisual** [comment]
I just upgraded my global `gas` version to `4.1.3` and I get the same result.

**Comment by radiovisual** [comment]
Looking deeper, I found out that you have to be in the root directory when you call `gas push`, because all of the file uploads are relative the project's root directory (which gas knows how to find by searching recursively for the `.gas` directory). So my upload works if I do this instead:

```
for FILE in `ls build`; do gas push build/$FILE; done
```

**Comment by MaartenDesnouck** [comment]
Yes you can define the root folder.
You should do `gas unlink` in the current root folder and then `gas link projectId` in the build folder and that achieves what you want to do I believe. 
But that would mean that you have to do `gas push` in the build folder...
