### ISSUE TITLE
.gas dir contents

### ISSUE THREAD

**Issue by larvanitis** [MaartenDesnouck/google-apps-script#38]
Can you please explain how `local.json` and `remote.json` files are used? I mean, when do they updated, what is their content, should they be checked in git etc

Thanks!

**Comment by MaartenDesnouck** [comment]
local.json is the google format version of your local files
remote.json is the the google format version of your project how it is google drive atm

I would not check them into git.

You might want to check /.gas/ID into git; that way if you clone your project on another location; it is linked to the correct project in Google Drive

**Comment by larvanitis** [comment]
Thanks. You might want to add this info on the README. The git part is important.
