### ISSUE TITLE
Add support for directories

### ISSUE THREAD

**Issue by larvanitis** [MaartenDesnouck/google-apps-script#40]
**The Problem**

- GAS platform does not nativaly support directories but a flat file structure.
- gas tool **silently** ignores any directory and its contents when pushing/pulling.

**Stopgap Feature Request**

- During `push`, warn the user about any directories and the lack of such support and abort.

**Support Directories Feature Request**

- Add support for local directories.
- During `push`:
    - Prefix the filename of the uploaded files with their path, using something like `$$` as separator.
        - eg `lib/data.js` -> `lib$$data.gs`
    - Empty directories (and `.gas/` of course) should be ignored.
    - Files with `$$` in their name should not be allowed. Warn the user about such files abort the push.
- During `pull`, parse filenames and reconstruct the file structure.
    - eg `lib$$data.gs` -> `lib/data.js`
- Bonus points for a configurable path separator!

**Comment by MaartenDesnouck** [comment]
Something for this weekend probably... shouldn't be to hard.

Won't do a configurable path separator, I don't like that.

**Comment by MaartenDesnouck** [comment]
Published 1.6.0
Should map folder in a 1-on-1 relationship with code files with slashes in them. 
```lib/data.js <-> lib/data.gs```
Enjoy.
