### ISSUE TITLE
Bad Request upon gas push/deploy

### ISSUE THREAD

**Issue by rcanu** [MaartenDesnouck/google-apps-script#43]
I edited my code in Atom when I invoke `gas push` and/or `gas deploy` this is shown

```
Pushing code to Google Drive... [✘]
gas returned an error: Error: Bad Request
```

**Comment by rcanu** [comment]
I was able to make it work. It seems that I needed to resync the project by invoking `gas pull` before deploying.

**Comment by MaartenDesnouck** [comment]
A bad request error usually means a syntax error in your local code. Google won't accept code with syntax errors in the API call used in 'gas push/deploy'

Let me know if anything else comes up!

**Comment by rcanu** [comment]
Thanks for the clarification @MaartenDesnouck! 👍🏻
