### ISSUE TITLE
Add testcase for drive with 100+ scripts

### ISSUE THREAD

**Issue by MaartenDesnouck** [MaartenDesnouck/google-apps-script#49]

**Comment by oshliaer** [comment]
# 100+ files

## pageSize
The best way is to low [the pageSize parameter](https://github.com/MaartenDesnouck/google-apps-script/blob/master/lib/functions/listScriptFiles.js#L26) before the tests.

## Recursive search by id
If the search file by `id` (not by tittle) is found at the next iteration, it will be found never. https://github.com/MaartenDesnouck/google-apps-script/blob/master/lib/functions/listScriptFiles.js#L20

How can I help? What I should to do?

**Comment by MaartenDesnouck** [comment]
Don't worry, ill fix it this evening (UTC)

**Comment by MaartenDesnouck** [comment]
Fixed in 1.6.6
