### ISSUE TITLE
Improve error message on 400 error

### ISSUE THREAD

**Issue by MaartenDesnouck** [MaartenDesnouck/google-apps-script#67]
<strike>- don't check html files for js errors, duh.</strike>
<strike>- only print that it is an syntax error if we find one</strike>
- make list of other possible 400 errors

**Comment by rcanu** [comment]
Somehow this item left me stuck. Will a force flag `-f` on `gas push` be possible?

**Comment by MaartenDesnouck** [comment]
No, Google just won’t let you push certain stuff but does not say why. Gas is able to recognize some of the problems when you can’t push but there are clearly some missing :/

**Comment by rcanu** [comment]
I see. Thanks @MaartenDesnouck 
Will see if I can contribute on this.

**Comment by MaartenDesnouck** [comment]
Should be better in 4.0.0 will reopen if comes up again
