### ISSUE TITLE
Init script failes

### ISSUE THREAD

**Issue by truepants** [MaartenDesnouck/google-apps-script#68]
I love this cli, it works perfect if you have a few Google Apps script files in your Google Drive. I develop a lot of Google Apps scripts for different customers this makes that I have a lot of scripts in my Google Drive approximately 300+. When I try to link a script by fileId it just wont link. See attached output (v2.2.1). Even if I create the script by the cli, it gets created in Google Drive, but doesn't clone the files.

![screen shot 2017-08-24 at 10 16 10](https://user-images.githubusercontent.com/27806205/29656699-8c8a9090-88b5-11e7-9a98-24f00dcdc278.png)

**Comment by MaartenDesnouck** [comment]
Hmmm. Thanks for reporting the issue!

**Comment by MaartenDesnouck** [comment]
@truepants Should be fixed. Let me know if anything comes up.
(Any features you are missing in 'gas' btw?)

**Comment by truepants** [comment]
@MaartenDesnouck Thanks for the quick fix. It works like a charm.
Well maybe something like templating or a default application structure. 
Or OTAP environments. I work for large customers in NL and UK and they all use OTAP like environments. Mostly it's not only a script but the whole project directory should be copied.

Maybe we can discuss some features in a hangout?

**Comment by MaartenDesnouck** [comment]
@truepants Hmmm interesting. And I'm up for discussing features in a hangouts.
