### ISSUE TITLE
Option to save source code in subdirectory

### ISSUE THREAD

**Issue by ina6ra** [MaartenDesnouck/google-apps-script#7]
It is a wonderful module!!
The following points are superior to ``node-google-apps-script`` and I want to expect in the future.

1. Easier authentication.
1. List function is convenient.
1. I can pull as well as deploy.

I think that it becomes a module exceeding ``node-google-apps-script`` if the following two functions are added.

1. Save source file in ``src`` subdirectory.
1. Open in browser with ``open`` command.

With 1, ``mocha`` will make testing easier.
``node-google-apps-script`` seems to be made conscious of it.

2 is not required.

**Comment by MaartenDesnouck** [comment]
Thanks for the feedback, guess i'll work on those :)

**Comment by MaartenDesnouck** [comment]
I'll be implementing remote link this week.

'remote link <fileId>' to link a remote Google Drive project to your current folder

This should give you full freedom regarding your local project structure.
You will de able to do: 
```
$ mkdir src
$ cd src
$ gas remote link <fileId>
$ gas pull
```

**Comment by MaartenDesnouck** [comment]
gas open has also been implemented

```
$ cd src
$ gas open
```
or
```
$ gas open some-file-id
```

So time for 'npm i -g google-apps-script', and tell me what you think.
