### ISSUE TITLE
.gs vis .js file extension

### ISSUE THREAD

**Issue by radzisz** [MaartenDesnouck/google-apps-script#70]
I'm using google-apps-script in a combinatin with chrome extention: google-apps-script enabling direct synchronization between GDrive and GitHub - they are using different strategy for naming server-side JS files (the extension is gs. not .js). 
Having a project pulled from github the  script files get *.gs so pushing it from my local drive back (to other gDrive account) results in script that is not seen by google script editor.
Do you consider a naming strategy that could address this issue?

**Comment by MaartenDesnouck** [comment]
Makes perfect sense to give the files the .gs extension and I will make changes to not only allow .gs but to make it the default extension. Just need to be toughtful about how to make that transition because everyone now using gas has the .js extension for their script files.

**Comment by radzisz** [comment]
I would start with adding a param --changeExtentionsJS2GS which by default false.
Than with major update would make it true by default but enable users to switch it to false.
Someday remove completely..

**Comment by MaartenDesnouck** [comment]
Decided to keep .js files the standard but .gs are supported for push. (Might change my mind in the future)

Won't make the complete switch or add the option because 
- editors don't know the .gs file extension
- I'd like to keep the code and everything I need to think about simple

**Comment by MaartenDesnouck** [comment]
@radzisz Decided to implement the .gs option anyway. Its available in 2.7.0. '$ gas config' to set it up.
