### ISSUE TITLE
how secure is having the Firebase secret in the end-user code ?

### ISSUE THREAD

**Issue by JeanRemiDelteil** [MaartenDesnouck/google-apps-script#75]
In _constant.js_ file the firebase client secret is plainly available.

This seems like a security issue and a bad practice.

**Comment by MaartenDesnouck** [comment]
Yeah, you're probable right. Will look into it.

**Comment by JeanRemiDelteil** [comment]
Maybe moving some part of the code in a Firebase or Cloud function will do
the trick.
This part would handle all authentication and user registering part.


Jean-Rémi Delteil,
Awesome Table team

Le 25 oct. 2017 20:58, "Maarten Desnouck" <notifications@github.com> a
écrit :

**Comment by MaartenDesnouck** [comment]
Thanks for the excellent solution to the problem. Fixed and changed keys in 2.6.0
