### ISSUE TITLE
TypeError: process.stdout.clearLine is not a function

### ISSUE THREAD

**Issue by yfaway** [MaartenDesnouck/google-apps-script#76]
If I run the command within a screen section, trying to do gas push will ead to this error:

>Pushing_ code to Google Drive... [✘]
>gas returned an error: TypeError: process.stdout.clearLine is not a function [✘]

Searching online a bit, and I see this reference:
>Don't use clearLine if stdout is not a tty. Fixes #20.
>https://github.com/onury/grunt-jasmine-nodejs/issues/20

**Comment by MaartenDesnouck** [comment]
You are correct in determining the problem, will see if I can fix this...

**Comment by MaartenDesnouck** [comment]
@yfaway Should be fixed in 2.3.1, let me know if it works.
("npm i -g google-apps-script" to get the latest version)

**Comment by yfaway** [comment]
That works. Thanks!
