### ISSUE TITLE
Pulls down appsscript.json as appsscript.js

### ISSUE THREAD

**Issue by wulftone** [MaartenDesnouck/google-apps-script#78]
It doesn't seem to work well with gmail add-ons--it pulls down the `appsscript.json` file as a `.js` file instead, and when you push back up it rejects it because of syntax errors... if you rename it to `.json` it then pushes up fine but your project generates a new (bad) `appsscript.json` file automatically and you lose all of your project metadata.  You can solve this by copying your old `appsscript.json` file back, but this is a bit wacky.

**Comment by MaartenDesnouck** [comment]
Aha, yes that would explain some issues. Thanks for reporting! Will fix that today.

**Comment by MaartenDesnouck** [comment]
@wulftone Should be fixed in 2.4.0, let me know if it works.
("npm i -g google-apps-script" to get the latest version)

**Comment by wulftone** [comment]
Hmm something seems amiss, not sure if it's related to your changes: ```$ gas link "my project"
Linking 'my project' to this folder... [✔]
 $ gas auth
You are successfully authenticated as 'correct@email.com' [✔]
 $ gas pull
Pulling 'my project' from Google Drive... [✘]
gas returned an error: Error: ENOENT: no such file or directory, stat 'node_modules/gtoken/node_modules/.bin/mime' [✘]
 $ 
```
