### ISSUE TITLE
How to create a file with a folder

### ISSUE THREAD

**Issue by ina6ra** [MaartenDesnouck/google-apps-script#8]
```
Go to a folder and create a new project.
$ gas new <name>
```

I executed it with reference to the README but the folder was not created.

```
$ gas new ina6ra/new-file
```

Can not I create a file with a folder?

**Comment by MaartenDesnouck** [comment]
At this point you can only create a new empty project.
You can then copy your .js and .html files into that folder, cd to that folder and do
```$ gas deploy```

Maybe a command creating could be useful... 
I will definitely think about it.
