### ISSUE TITLE
Random push failures

### ISSUE THREAD

**Issue by wulftone** [MaartenDesnouck/google-apps-script#82]
I can `gas push` several times in a row and sometimes it works, sometimes it fails--with zero changes to files.  A couple of times it even erased all of my code on Drive and put a "gas" fail file there instead.

```bash
Pushing 'My app' to Google Drive... [✘]
Google doesn't accept the code you are trying to push. Try doublechecking for project structure errors. Push was reverted. [✘]
Pushing 'My app' to Google Drive... [✘]
Google doesn't accept the code you are trying to push. Try doublechecking for project structure errors. Push was reverted. [✘]
Pushing 'My app' to Google Drive... [✔]
```

**Comment by MaartenDesnouck** [comment]
That's not good...

**Comment by MaartenDesnouck** [comment]
The gas placeholder file is an architectural choice I made; the alternative would be to match all the file-ids in a project to the right names on your local machine. It also allows me to put files alphabetically in Google Drive. Maybe I could put in more failsafes to revert code in that case, or just make that trade off.

That being said. The push failing with zero changes to files is something I did not know, and have never encountered myself... Is this happening on more than 1 project or in certain instances?

**Comment by MaartenDesnouck** [comment]
( a copy of your local.json in the .gas directory would be of enormous help)

**Comment by wulftone** [comment]
Unfortunately I can't share that because it contains proprietary source code, but I'll see what I can dig up... I'm experimenting now to try to figure out how to get my code pushed back up... wish the error messages were more descriptive (I understand you're limited by Google's responses)

**Comment by wulftone** [comment]
Here's one little thing I found: 
```bash
$ gas push appsscript.json
Pushing 'My App > appsscript.json' to Google Drive... [✘]
```

**Comment by MaartenDesnouck** [comment]
Ow. Yes that one is definitely my fault.

**Comment by MaartenDesnouck** [comment]
Totally understand not sharing code btw. And yes I'm limited by a simple 400 Bad request from Google's side. Im able to triage some errors but I could definitely do better.

**Comment by MaartenDesnouck** [comment]
Publish 2.4.1 and that should fix the 
"gas returned an error: TypeError: eaft.isValidExtension is not a function [✘]" -bug
("npm i -g google-apps-script" to get the latest version)

**Comment by MaartenDesnouck** [comment]
Going to turn that placeholder flow upside down on Wednesday because having that state in any case is pretty unacceptable.

**Comment by wulftone** [comment]
Yeah unfortunately I have to stop using this method of pushing code because it keeps deleting all of mine.  : (  I might have some time to dig into it this weekend but in the meantime I have to ship features!

**Comment by wulftone** [comment]
Do you have a gmail addon project to test with? There might be some quirks specific to those types of addons since they're brand new.

**Comment by wulftone** [comment]
Thanks for the recent updates, it seems to work fine these days!
