### ISSUE TITLE
Optional possibility to use our own project (for Drive access)

### ISSUE THREAD

**Issue by JeanRemiDelteil** [MaartenDesnouck/google-apps-script#88]
Hi again,

As security and secure scope usage is an increasing focus from Google and for client expectation about security, it should be possible to use our own project to access Drive & scripts and not give access to an external application.

I'm aware of the complexity of this request and at this time I don't have a ready made solution for this.
However I feel that this would be a show stopper for some company to use this with Apps script projets.

The previous CLI for this (https://www.npmjs.com/package/node-google-apps-script) did use a locally stored token (which is not really secure), but it allowed to not give any external access. (for example)

**Comment by MaartenDesnouck** [comment]
Makes sense to allow an config file with a clientId and clientSecret to overwrite the default app if you want.

**Comment by MaartenDesnouck** [comment]
Hey, @JeanRemiDelteil this feature should be available in 2.7.0.
'gas config' will guide you trough the setup.

**Comment by JeanRemiDelteil** [comment]
It works well !
Though we have to not forget to add the http://localhost:9012 to the authorized redirect URLs

**Comment by MaartenDesnouck** [comment]
Ah yes! 
(Ill have to write a 'how to set up a custom client'-readme part maybe)

**Comment by JeanRemiDelteil** [comment]
I've already written this for my team, maybe you can use it (though I used
images :p ):



To configure the commande line tool GAS to use your project credentials use:


> gas config



[image: Inline images 3]


To fill in the client ID and client Secret, you will have to use a Google
project.
You can either directly create a new project here:
https://console.cloud.google.com/projectcreate
Or (if you were previously using the gapps command line tool) re-use an
Apps Script project:

Here is you to access to the Google Project behind the apps script file (DO
NOT use this apps script for anything, it's just to have credentials):

[image: Inline images 2]


Then, in the Google project > APIs & Services > Credentials, create a new
Credentials for OAuth client ID > web application:

- use a comprehensive name
- Add to the redirect URLs: *http://localhost:9012 <http://localhost:9012/>*

[image: Inline images 4]


It will then gives you the *Client ID* and *Client Secret* needed as input
to the gas config command.

If it was not activated before, *you have to activate the Drive API* for
this project:

[image: Inline images 5]





*Jean-Rémi*
*Awesome Table
<https://sites.google.com/site/scriptsexamples/available-web-apps/awesome-tables>
*
Team
awesome-table.com

**Comment by MaartenDesnouck** [comment]
Ah nice!
