### ISSUE TITLE
Can't get rid of association with a test project

### ISSUE THREAD

**Issue by dompardoe** [MaartenDesnouck/google-apps-script#95]
Hi Maarten

Tested this out with a test script. Worked fantastic. Now I cannot lose the link with the test script when trying to clone my actual libraries - it always reports 

'You seem to be cloning a project inside another project. Cowardly chose not to do that. '

I have created new folders, forced re-authentication, uninstalled google-apps-script from node, uninstalled node itself, but still the association seems to persist.

I can't push, pull, nothing

Does it store some temporary files somewhere that I can remove?

**Comment by MaartenDesnouck** [comment]
Yes, it does. Look for a hidden .gas folder and just throw that folder out completely.
Might add an unlink command if its a valid use case.

**Comment by dompardoe** [comment]
Aha, I had accidentally created a .gas folder in a higher level directory which was stopping me from working with anything below it. Thankyou.
