### ISSUE TITLE
Take a look at team drives and other shared scripts

### ISSUE THREAD

**Issue by MaartenDesnouck** [MaartenDesnouck/google-apps-script#98]

**Comment by nicolairobles** [comment]
Definitely need this. All of my scripts are in shared folders with other teams. 

Currently no tool allows access to shared scripts.

**Comment by MaartenDesnouck** [comment]
@nicolairobles I have the code ready to support TeamDrives (push, pull, rename and delete scripts) but shared scripts (shared with a specific user) should  work in the current version already. Did you mean you need team drives? Don't want to release the code if it does not solve your use-case.

**Comment by nicolairobles** [comment]
@MaartenDesnouck  here's some background. My main use-case is working with [container-bound apps scripts](https://developers.google.com/apps-script/guides/bound). For me, the scripts get generated from google sheets tied to Google Forms. 

For some reason they don't show up as belonging to me when I run the below command. I'm really just discovering now that there's a difference between container-bound scripts and other free-bound scripts.
`gas list`

**Comment by MaartenDesnouck** [comment]
I have done some research in the past but I'm 99% sure that container bound scripts can't be accessed via the API. Which is unfortunate. (https://developers.google.com/apps-script/guides/import-export)
